name: CI/CD
run-name: "CI/CD @${{ github.ref_name }}"
on:
  push:
    branches:
      - main
    tags:
      - "!*"
  pull_request:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
  GH_USER: "github-actions[bot]"

jobs:
  prepare:
    name: Release check
    if: github.repository == 'mato533/rollup-plugin-gas'
    runs-on: ubuntu-latest
    outputs:
      is_release: ${{ steps.release-decision.outputs.is_release }}
      app_version: ${{ steps.identify-version.outputs.app_version }}
      app_version_text: ${{ steps.identify-version.outputs.app_version_text }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Identify the version about to release
        id: identify-version
        run: |
          APP_VERSION="$(cat ./package.json |jq .version|sed -e 's/"//g'| head -n1)"
          if [ ! -n "${APP_VERSION}" ]; then
            exit 255
          fi
          echo "Detected the version: ${APP_VERSION}"
          echo "app_version=${APP_VERSION}" >>"${GITHUB_OUTPUT}"
          echo "app_version_text=v${APP_VERSION}" >>"${GITHUB_OUTPUT}"

      - name: Check the version
        id: check-diff-version
        run: |
          DIFF_COUNT="$(git diff HEAD HEAD^ --relative package.json |grep '"version":'|wc -l)"
          VAR_NAME="is_update_version"
          if [ ${DIFF_COUNT} -eq 2 ]; then
            echo "Detected to have updated the version in package.json"
            echo "${VAR_NAME}=1" >>"${GITHUB_OUTPUT}"
          else
            echo "The version in package.json is not updated"
            echo "${VAR_NAME}=0" >>"${GITHUB_OUTPUT}"
          fi

      - name: Check the commit message
        id: check-commit-msg
        run: |
          echo 'Start the release process when the commit message contains the string "release" and the version value in package.json'
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          COMMIT_MSG_LOW="$(echo "${COMMIT_MSG,,}")"
          COUNT_RELEASE="$(echo "${COMMIT_MSG_LOW}" | grep "release" | wc -l)"
          COUNT_VERSION="$(echo "${COMMIT_MSG_LOW}" | grep "${{steps.identify-version.outputs.app_version}}" | wc -l)"
          VAR_NAME="is_release_commit"
          if [ ${COUNT_RELEASE} -gt 0 ] && [ ${COUNT_VERSION} -gt 0  ]; then
            echo "Judged from the commit message that it is subject to release processing."
            echo "${VAR_NAME}=1" >>"${GITHUB_OUTPUT}"
          else
            echo "This commit is not  subject to release processing."
            echo "${VAR_NAME}=0" >>"${GITHUB_OUTPUT}"
          fi

      - name: Decision to start release process
        id: release-decision
        run: |
          echo "Release judgment based on update of package.json version value or commit message"
          IS_UPDATE_VER=${{ steps.check-diff-version.outputs.is_update_version }}
          IS_RELEASE_COMMIT=${{ steps.check-commit-msg.outputs.is_release_commit }}
          VAR_NAME="is_release"
          if [ ${IS_UPDATE_VER} -gt 0 ] || [ ${IS_RELEASE_COMMIT} -gt 0 ]; then
            echo "Steart Release process"
            echo "${VAR_NAME}=1" >>"${GITHUB_OUTPUT}"
          else
            echo "Skip Release process"
            echo "${VAR_NAME}=0" >>"${GITHUB_OUTPUT}"
          fi

  test:
    name: Test & build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup node (${{ matrix.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run the test
        run: pnpm run test

      - name: Run the test for typescripts
        run: pnpm run test:ts

      - name: Run the test for build
        run: pnpm run build

  publish:
    name: Publish to the NPM registry
    needs:
      - prepare
      - test
    if: ${{ needs.prepare.outputs.is_release > 0 }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install

      - name: Run the build
        run: |
          pnpm run build

      - name: Publish
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  coverage:
    name: Upload the coverage
    needs:
      - prepare
      - test
    if: ${{ needs.prepare.outputs.is_release > 0 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run the coverage
        run: pnpm run coverage

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json
          verbose: true

  tag:
    name: Add the tag for the released version
    needs:
      - prepare
      - publish
    if: ${{ needs.prepare.outputs.is_release > 0 }}
    runs-on: ubuntu-latest
    env:
      VERSION_TAG: ${{ needs.prepare.outputs.app_version_text }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Github user informations.
        run: |
          git config --local user.email "${{ env.GH_EMAIL }}"
          git config --local user.name "${{ env.GH_USER }}"

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Add the release tag
        run: |
          git tag "${VERSION_TAG}"
          git push origin "${VERSION_TAG}"

      - name: Generate changelog
        env:
          GITHUB_REPO: ${{ github.repository }}
        run: |
          pnpm run changelog -c cliff-github.toml -l
          pnpm exec prettier --write CHANGELOG.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ needs.prepare.outputs.app_version_text }}
          release_name: ${{ needs.prepare.outputs.app_version_text }}
          draft: false
          prerelease: false
          body_path: CHANGELOG.md
