name: Run Test
run-name: "TEST@${{github.ref_name}}"
on:
  workflow_call:

  push:
    branches:
      - main
    paths:
      - "*"
      - src/**
      - "!**.md"

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test & build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x]
    steps:
      - uses: mato533/cicd-actions/setup-pnpm@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Type check
        run: pnpm run typecheck

      - name: Run the test
        run: pnpm run test

      - name: Build
        run: pnpm run build
