name: Test for develop

on:
  push:
    branches:
      - feature/ci-setting

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup
      - name: Build
        run: yarn build

  test:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: ./.github/actions/setup
      - name: Test for unit
        run: yarn test
      - name: Test for Types
        run: yarn test:ts
