name: Test for develop

on:
  push:
    branches:
      - feature/ci-setting

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Unit test
        run: yarn test

      - name: Test for Types
        run: yarn test:ts

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Test for lint
        run: yarn run lint

      - name: Test for format
        run: yarn run format
