name: Release check (preparation)
on:
  workflow_call:
    outputs:
      app-version:
        description: "version (1.0.0)"
        value: ${{ jobs.get-version.outputs.app-version }}
      app-version-text:
        description: "version (v1.0.0)"
        value: ${{ jobs.get-version.outputs.app-version-text }}
jobs:
  get-version:
    name: Get versioon from package.json
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.identify-version.outputs.app-version }}
      app-version-text: ${{ steps.identify-version.outputs.app-version-text }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Parse package.json
        id: identify-version
        run: |
          APP_VERSION="$(cat ./package.json |jq .version|sed -e 's/"//g'| head -n1)"
          if [ ! -n "${APP_VERSION}" ]; then
            exit 255
          fi
          echo "Detected the version: ${APP_VERSION}"
          echo "app-version=${APP_VERSION}" >>"${GITHUB_OUTPUT}"
          echo "app-version-text=v${APP_VERSION}" >>"${GITHUB_OUTPUT}"
